### ISSUE TITLE
Z3 download 404

### ISSUE THREAD

**Issue by zsfre** [cwi-swat/rebel2#6]
Z3 now available at https://github.com/Z3Prover/z3

**Comment by joukestoel** [comment]
Thanks! I have just updated the readme

**Comment by zsfre** [comment]
turns out to also be available via homebrew

**Comment by joukestoel** [comment]
True, but I think that this is an older version. I am on Z3 version 4.8.8

**Comment by joukestoel** [comment]
Sorry, it seems that the homebrew version was updated to 4.8.10
