### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by zsfre** [cwi-swat/rebel2#7]
OS/X
Eclipse DSL Tools (includes Incubating components)

Version: 2020-12 (4.18.0)
Build id: 20201210-1552

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: allealle_feature 0.1.0.202102261238 (allealle_feature.feature.group 0.1.0.202102261238)
  Missing requirement: allealle 0.1.0.202102161356 (allealle 0.1.0.202102161356) requires 'osgi.bundle; rascal_eclipse 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: allealle_feature 0.1.0.202102261238 (allealle_feature.feature.group 0.1.0.202102261238)
    To: org.eclipse.equinox.p2.iu; allealle [0.1.0.202102161356,0.1.0.202102161356]
```

**Comment by joukestoel** [comment]
Hi @zsfre , it looks like Rascal itself is missing from your installation. Did you install:
a) [Eclipse RAP/RCP version 2020-06](https://www.eclipse.org/downloads/packages/release/2020-06/r/eclipse-ide-rcp-and-rap-developers)?
b) [Rascal Stable version](https://www.rascal-mpl.org/start/)?
c) Java JDK 8?

**Comment by zsfre** [comment]
Doh! Didn't read that part. Not sure I even have Java 8 any more.

**Comment by joukestoel** [comment]
Hahaha, I know. It is not the nicest dependency and we (on the Rascal side) are working on fixing it :s but this requires quite some effort.

Don't hesitate to open more issues if you run into trouble!
